export const EMBER_ROUTE_ACTIVATED = 'ember@@ROUTE_ACTIVATED';
export const EMBER_ROUTE_DEACTIVATED = 'ember@@ROUTE_DEACTIVATED';
export const EMBER_ROUTE_PARAMS_LOADED = 'ember@@ROUTE_PARAMS_LOADED';
export const EMBER_ROUTE_MODEL_RESOLVED = 'ember@@ROUTE_MODEL_RESOLVED'

export const DS_FIND_RECORD_REQUESTED = 'ds@@FIND_RECORD_REQUESTED';
export const DS_FIND_RECORD_SUCCEEDED = 'ds@@FIND_RECORD_SUCCEEDED';
export const DS_FIND_RECORD_FAILED = 'ds@@FIND_RECORD_FAILED';

export const EMBER_DS_RESET_STATE = 'ember+ds@@DS_RESET_STATE';
