export const EMBER_ROUTE_ACTIVATED = 'ember@@ROUTE_ACTIVATED';
export const EMBER_ROUTE_DEACTIVATED = 'ember@@ROUTE_DEACTIVATED';
export const EMBER_ROUTE_PARAMS_LOADED = 'ember@@ROUTE_PARAMS_LOADED';
export const EMBER_ROUTE_MODEL_RESOLVED = 'ember@@ROUTE_MODEL_RESOLVED';
export const EMBER_ROUTE_ARRAY_RESOLVED = 'ember@@ROUTE_ARRAY_RESOLVED';
export const EMBER_ROUTE_POJO_RESOLVED = 'ember@@ROUTE_POJO_RESOLVED';
export const EMBER_ROUTE_CHANGESET_RESOLVED = 'ember@@ROUTE_CHANGESET_RESOLVED';

export const DS_FIND_RECORD_REQUESTED = 'ds@@FIND_RECORD_REQUESTED';
export const DS_FIND_RECORD_SUCCEEDED = 'ds@@FIND_RECORD_SUCCEEDED';
export const DS_FIND_RECORD_FAILED = 'ds@@FIND_RECORD_FAILED';
export const DS_QUERY_COLLECTION_REQUESTED = 'ds@@QUERY_COLLECTION_REQUESTED';
export const DS_QUERY_COLLECTION_SUCCEEDED = 'ds@@QUERY_COLLECTION_SUCCEEDED';
export const DS_QUERY_COLLECTION_FAILED = 'ds@@QUERY_COLLECTION_FAILED';
export const DS_CHANGESET_PERSIST_FAILED = 'ds@@CHANGESET_PERSIST_FAILED';
export const DS_CHANGESET_PERSIST_SUCCEEDED = 'ds@@CHANGESET_PERSIST_SUCCEEDED';
export const DS_CHANGESET_MODIFIED = 'ds@@CHANGESET_MODIFIED';
export const DS_CHANGESET_CREATED = 'ds@@CHANGESET_CREATED';
export const DS_CHANGESET_CLEARED = 'ds@@CHANGESET_CLEARED';
export const DS_CHANGESET_AFTER_SUCCESS_HOOKED = 'ds@@CHANGESET_AFTER_SUCCESS_HOOKED';
export const DS_CHANGESET_AFTER_FAILURE_HOOKED = 'ds@@CHANGESET_AFTER_FAILURE_HOOKED';
export const DS_CHANGESET_BEFORE_PERSIST_HOOKED = 'ds@@CHANGESET_BEFORE_PERSIST_HOOKED';

export const EMBER_DS_RESET_STATE = 'ember+ds@@DS_RESET_STATE';
